Fix for: Border in table is not applied to last <td> if its inside a dom-if (#63)
Starcounter/underwear.css pull request #66
Opened 2018-03-01 16:47 UTC by warpech

Change the selector to `:last-of-type`

because otherwise, it did not apply if there was a `<template>` as the last element of `<tr>`

Solves #63

2018-03-02 14:57 UTC, alshakero reviewed
I couldn't manage to create a working table with the setup in #63 

https://jsbin.com/lemale/1/edit?html,css,output. Am I making a mistake?

2018-03-02 14:59 UTC, alshakero approved these changes
Other than the comment above the CSS itself LGTM

2018-03-02 15:42 UTC, warpech commented
I think that's the way to reproduce it

Before: https://jsbin.com/cifuwul/3/edit?html,css,output

After: https://jsbin.com/cifuwul/2/edit?html,css,output

2018-03-02 16:02 UTC, alshakero requested changes
Hold on. The bug is still there I think.

2018-03-02 16:03 UTC, alshakero approved these changes
My bad. All perfect. Thanks for the JSBin!

2018-03-04 20:21 UTC, warpech commented
Thanks for the review! Merging

2018-03-04 20:21 UTC, merged